#!/bin/bash 

echo "DEPLOY"
ssh -t root@ratinator.ly <<REMOTE
cd ratinatorly 

# checkout
echo 'Checking out code'
git fetch
git reset --hard origin/master 

# install deps
echo 'Installing'
npm install

# start the server
echo 'Restarting'
stop ratinatorly
start ratinatorly

REMOTE
